# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apiuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='user',
            new_name='username',
        ),
    ]
