# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170518_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='adding_permissions',
        ),
    ]
