# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_apiuser_adding_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adding_permissions',
            field=models.BooleanField(default=True),
        ),
    ]
