# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_adding_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adding_permissions',
        ),
    ]
