# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-19 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170519_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adding_permissions',
            new_name='user_permissions',
        ),
    ]
