# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170519_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adding_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
